### ISSUE TITLE
styling Option Elements

### ISSUE THREAD

**Issue by neridonk** [jqm4gwt/jqm4gwt#96]
hey i tryed to style in a select the Option element via :  

		NodeList<OptionElement> options = list.getOptions();

		for (int i = 0; options.getLength() > i; i++)
		{
			options.getItem(i).setInnerHTML("<p style=\"font-size:12px; \"> " +              options.getItem(i).getInnerHTML() + "<p>");
		}

		offeneAntraege.refresh();

but this doesnt work .... can u give me tipps

**Comment by slavap** [comment]
You can do that with plain CSS, no need to set style in java code.

See http://stackoverflow.com/a/14386328/714136

It's for jqm <= 1.3.2, in current version generated DOM structure is changed, so you have to replace CSS this way to make it working in 1.4.5:
```css
#Droplet-menu li:nth-child(1) .ui-btn {background-color:Red; }
#Droplet-menu li:nth-child(1) .ui-btn {color: #FFFFFF !important; text-shadow: #3373A5 0px 1px 1px}

#Droplet-menu li:nth-child(2) .ui-btn {background-color:Blue;}
#Droplet-menu li:nth-child(2) .ui-btn {color: #FFFFFF !important; text-shadow: #3373A5 0px 1px 1px}
 ...
```
